<nav class="navbar navbar-expand-lg menu">
    <div class="container">
        <div class="navbar-nav">
            <a class="menuItem" href="/timeline">
                Home
            </a>

            <a class="menuItem" href="/logoff">
                Logoff
            </a>
            <img src="/img/twitter_logo.png" class="menuIco" />
        </div>
    </div>
</nav>

<div class="container mt-5">
    <div class="row pt-2">

        <div class="col-md-3">
            <div class="profile">
                <div class="profileTop">

                </div>

                <div class="profilePanel">

                    <div class="row mt-2 mb-2">
                        <div class="col mb-2">
                            <span class="profilePanelName">
                                <?= $this->view->user_information['nm_user'] ?>
                            </span>
                        </div>
                    </div>

                    <div class="row mb-2">

                        <div class="col">
                            <span class="profilePanelItem">Tweets</span><br />
                            <span class="profilePanelItemValue">
                                <?= $this->view->total_tweets['total_tweets'] ?>
                            </span>
                        </div>

                        <div class="col">
                            <span class="profilePanelItem">Following</span><br />
                            <span class="profilePanelItemValue">
                                <?= $this->view->total_following['total_following'] ?>
                            </span>
                        </div>

                        <div class="col">
                            <span class="profilePanelItem">Followers</span><br />
                            <span class="profilePanelItemValue">
                                <?= $this->view->total_followers['total_followers'] ?>
                            </span>
                        </div>

                    </div>

                </div>
            </div>
        </div>

        <div class="col-md-6">

            <div class="row mb-2">
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <form action="/who_to_follow" method="get">
                                <div class="input-group mb-3">
                                    <input type="text" name="searchFor" class="form-control" placeholder="Who are you looking for?">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="submit">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <?php foreach($this->view->users as $index => $user) { ?>
                <div class="row mb-2">
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <?= $user['nm_user'] ?>
                                    </div>
                                    
                                    <div class="col-md-6 d-flex justify-content-end">
                                        <div>
                                            <?php if($user['following_yn'] == 0) { ?>
                                                <a href="/action?action=follow&id_user=<?=$user['id_user']?>" class="btn btn-success">Follow</a>
                                            <?php } ?>
                                            <?php if($user['following_yn'] == 1) { ?>
                                                <a href="/action?action=unfollow&id_user=<?=$user['id_user']?>" class="btn btn-danger">Unfollow</a>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
                
        </div>
    </div>
</div>