<div class="container-fluid h-100">
    <div class="row d-flex flex-row-reverse h-100">

        <div class="col-md-6 p-5">
            <form action="/authenticate" method="post">
                <div class="row">
                    <div class="col-12 col-md-4 my-2">
                        <input type="text" name="email" class="form-control" placeholder="E-mail">
                    </div>
                    <div class="col-12 col-md-4 my-2">
                        <input type="password" name="password" class="form-control" placeholder="Password">
                    </div>
                    <div class="col-12 col-md-4 my-2">
                        <button type="submit" class="btn btn-primary mb-2">Login</button>
                    </div>
                </div>

                <?php if($this->view->login == 'error') { ?>
                    <div class="row">
                        <div class="col">
                            <span class="text text-danger">*Invalid email or password</span>
                        </div>
                    </div>
                <?php } ?>
            </form>

            <div class="row">
                <div class="col pt-5">
                    <img src="/img/twitter_logo.png" />
                    <h1 class="title">See what's going on in the world now</h1>

                    <h2 class="mt-5 subtitle">Join Twitter today.</h2>
                    <a href="/signup" class="btn btn-primary btn-block mb-2">Sign up</a>
                </div>
            </div>
        </div>

        <div class="col-md-6 p-5 banner">
            <div class="row justify-content-center align-items-center">
                <div>
                    <div class="communicationItem">
                        <i class="fas fa-search fa-2x mr-3"></i>
                        Follow what interests you.
                    </div>
                    <div class="communicationItem">
                        <i class="fas fa-user-friends fa-2x mr-3"></i>
                        Know what people are talking about.
                    </div>
                    <div class="communicationItem">
                        <i class="far fa-comment fa-2x mr-3"></i>
                        Join the conversation.
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>