<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <div class="card" style="width: 36rem;">
            <div class="card-body">

                <div class="d-flex justify-content-center">
                    <img src="/img/twitter_logo.png" />
                </div>

                <div class="row">
                    <div class="col">
                        <h2>Create your account</h2>
                    </div>
                </div>

                <div class="row">
                    <div class="col">

                        <form action="/register" method="post">
                            <div class="form-group">
                                <input type="text" value="<?= $this->view->user['name'] ?>" name="name" class="form-control" placeholder="Name">
                            </div>

                            <div class="form-group">
                                <input type="text" value="<?= $this->view->user['email'] ?>" name="email" class="form-control" placeholder="E-mail">
                            </div>

                            <div class="form-group">
                                <input type="password" value="<?= $this->view->user['password'] ?>" name="password" class="form-control" placeholder="Password">
                            </div>

                            <div class="mt-4 mb-4">
                                <small class="form-text">
                                    By signing up, you agree to the Terms of Service and Privacy Policies, including the
                                    Use of Cookies. Others will be able to find you by email or phone number provided ·
                                    Privacy Options
                                </small>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Sign up</button>

                            <?php if($this->view->registrationError) { ?>
                                <small class="form-text text-danger">*Error when trying to register, check if the fields were filled out correctly.</small>
                            <?php } ?>
                        </form>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>